### ISSUE TITLE
安卓手机使用此demo的一些问题

### ISSUE THREAD

**Issue by huangwei110** [lirongtong/miitvip-scan-demo#1]
1、下载demo运行后，安卓手机访问，页面会不断刷新，不断提示获取手机权限
2、你们官网的demo和github的这个demo代码好像不一致，安卓手机访问你们官网的例子是可以正常使用的，但是调起的是手机的前置摄像头，而不是后置，希望大神你能将官网最新的代码更新到github，非常感谢！

**Comment by lirongtong** [comment]
刚开始做 Demo 的时候没有测试安卓机，只是为了验证 iPhone 内，除了自带浏览器 Safari 外，是不是其它的任何浏览器都拉不起来 ... 事实上是的 ... 没有权限。
我刚拿了小米6试了一下，用的浏览器是 UC，正常获取，且改为拉起后置摄像头了
