### ISSUE TITLE
为什么扫描后需要刷新才能再次识别？

### ISSUE THREAD

**Issue by gdfsjunjun** [lirongtong/miitvip-scan-demo#5]
请问可以做到连续识别吗？为什么要刷新才能再次扫描？
能问一下是哪里限制了吗？浏览器自己限制？我研究一下。

**Comment by lirongtong** [comment]
可以连续识别，调用不同的方法即可，我只是方便测试用的

发自我的iPhone

在 2021年4月24日，16:58，Jimmy 徐 ***@***.***> 写道：

﻿

请问可以做到连续识别吗？为什么要刷新才能再次扫描？
能问一下是哪里限制了吗？浏览器自己限制？我研究一下。
